### ISSUE TITLE
Which version of Swift to use?

### ISSUE THREAD

**Issue by drakeet** [chelseavalentine/Pomodoro#3]
The project is pretty cool! 

I am not familiar with iOS programming, and Xcode requires me to specify the Swift version, which version of Swift you are using? Thanks!

**Comment by chelseavalentine** [comment]
Sorry for the super late response! I finally released a working version of the app. This app is written in Swift 2.2 and I'm using Xcode 7.3.1.

Thanks for your interest! :)
